name: Build Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code with proper permissions
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21 using modern action version
      - name: Set up JDK 21 (Eclipse Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Create Release and Upload Artifact (only on push to main)
      - name: Create Release and Upload Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
          tag_name: v${{ github.run_number }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}